name: "sast-scan"

on:
  push:
    branches: [githubcicd]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt install npm
          sudo npm install --package-lock
          npm audit fix
             first

      - name: OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
          unzip dependency-check-6.0.2-release.zip

      - name: Run scan with ODC
        run: |
          dependency-check/bin/dependency-check.sh --project "bitcoin" --scan . > ODC-report

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sast report
          path: |
            ./ODC-report
